# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy backend to Firebase Cloud Functions

on:
  push:
    branches: [ "14-leaderboard-back-end", "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Run Python commands
      run: |
        pip install --upgrade pip
        python3.11 -m venv env
        source env/bin/activate
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
        pip install -r server/requirements.txt
    - name: Get the access files
      run: "echo \"${{ secrets.FIREBASE_TOKEN_FILE }}\" > server/.firebase.json"
    - uses: ProgrammerPeter2/deploy-firebase-functions@v0.1
      name: Deploy Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI_TOKEN }}
        FIREBASE_PROJECT: engame-quiz-ea63a
